
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - crunchybridge.com
  resources:
  - crunchybridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crunchybridge.com
  resources:
  - crunchybridges/finalizers
  verbs:
  - update
- apiGroups:
  - crunchybridge.com
  resources:
  - crunchybridges/status
  verbs:
  - get
  - patch
  - update
